name: SimpleBroadcast
main: com.simpleplugins.simplebroadcast.SimpleBroadcast
version: 1.1.2
api-version: "1.21"
description: "Simple Paper/Spigot plugin that sends automatic messages to the server chat."
author: "sardidefcon"

commands:
  simplebroadcast:
    description: SimpleBroadcast plugin commands
    usage: /<command> <reload|toggle>
    aliases: [sb]

permissions:
  sb.reload:
    description: Allows reloading the plugin configuration without restarting the server
    default: op
  sb.toggle:
    description: Allows pausing or resuming automatic message broadcasting
    default: op
